<a href="https://colab.research.google.com/github/sachinv16/Numpy/blob/main/Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np , pandas as pd
import matplotlib.pyplot as plt , seaborn as sns
from sklearn import linear_model

In [ ]:
df = pd.read_csv("Homepricenew2.csv")
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [ ]:
import math
df.bedrooms.median()

4.0

In [ ]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [ ]:
model = linear_model.LinearRegression()

In [ ]:
model.fit(df.drop('price',axis=1),df.price)

LinearRegression()

In [ ]:
model.predict([[3000,4,10]])

array([618748.66891723])

In [ ]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [ ]:
model.intercept_

221323.00186540384

In [ ]:
model.predict([[1000,3,10]])

array([371234.90495503])